import type { Metadata } from "next";
import { Vollkorn } from "next/font/google";
import "./globals.css";

const inter = Vollkorn({
  subsets: ['latin'],
  weight: '600',
});

export const metadata: Metadata = {
  title: "Puplanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
