import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Navbar } from "../app/component";
import { ClerkProvider } from '@clerk/nextjs'

import "./globals.css";

const font = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Puplanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={`${font.className} bg-gray-100`} >
          <Navbar />
          <div className="container min-h-[90vh] mx-auto px-4">{children}</div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

function Footer() {
  return (
    <footer className="bg-gray-800 text-white text-center py-4">
      <p>&copy; 2021 Puplanner</p>
    </footer>
  );
}
